# Generated by Django 4.2.7 on 2025-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
