[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && npm install && npx tailwindcss -i ./static/css/input.css -o ./static/css/styles.css && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn ecom_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/products"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "ecom_backend.settings"
DEBUG = "False" 