[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn ecom_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/products"
healthcheckTimeout = 10
restartPolicy = "on-failure"
maxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "ecom_backend.settings"
DEBUG = "False" 