# Generated by Django 4.2.7 on 2025-05-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0004_alter_cart_options_alter_cart_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
