# Generated by Django 4.2.7 on 2025-05-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_cart_options_alter_cart_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at", "name"]},
        ),
    ]
